export const APPROVALS_DB_CLIENT = Symbol("APPROVALS_DB_CLIENT");
export const APPROVALS_REPO = Symbol("APPROVALS_REPO");
export const APPROVALS_EVENTS_REPO = Symbol("APPROVALS_EVENTS_REPO");
export const APPROVAL_EXECUTOR_QUEUE = Symbol("APPROVAL_EXECUTOR_QUEUE");
export const TEMPORAL_CLIENT = Symbol("TEMPORAL_CLIENT");
