import type { NewPort } from "./schema/ports.js";
import { SEED_PORT_IDS } from "./seed-ids.js";

/**
 * Caribbean + US-gulf port seed (0020_ports). Hand-curated specs for
 * the 17 ports VTC trades most often — draft / LOA / DWT limits are
 * best-effort from public harbour-authority publications and should
 * be re-verified against the local agent's circular before
 * chartering. `lastVerifiedAt: null` on every row marks them as
 * "seeded, not yet confirmed".
 *
 * Region slugs match the freight_rates vocabulary ("caribbean" plus
 * "usgc" / "usec" / "uswc") so deal → port → lane joins don't need
 * a translation layer.
 *
 * Called from seed.ts after the workspace row lands. Insert is
 * idempotent via the (tenant, unlocode) unique index — re-running
 * seed is safe.
 */
export function caribbeanPortSeed(tenantId: string): NewPort[] {
  const now = new Date();
  const base = { tenantId, createdAt: now, updatedAt: now } as const;
  return [
    {
      ...base,
      id: SEED_PORT_IDS.JMKIN!,
      unlocode: "JMKIN",
      name: "Kingston",
      countryCode: "JM",
      region: "caribbean",
      lat: 17.9712,
      lng: -76.7936,
      maxDraftM: 12.2,
      maxLoaM: 300,
      maxBeamM: 40,
      maxDwtMt: 95_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: true,
      customsClearanceDaysMedian: 2,
      portDaysMedian: 2.5,
      congestionFactor: 1.1,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.JMMBJ!,
      unlocode: "JMMBJ",
      name: "Montego Bay",
      countryCode: "JM",
      region: "caribbean",
      lat: 18.4670,
      lng: -77.9190,
      maxDraftM: 11.0,
      maxLoaM: 260,
      maxBeamM: 35,
      maxDwtMt: 60_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: false,
      customsClearanceDaysMedian: 2,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "0700-1900",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.TTPOS!,
      unlocode: "TTPOS",
      name: "Port of Spain",
      countryCode: "TT",
      region: "caribbean",
      lat: 10.6538,
      lng: -61.5068,
      maxDraftM: 16.0,
      maxLoaM: 320,
      maxBeamM: 42,
      maxDwtMt: 120_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: true,
      customsClearanceDaysMedian: 1.5,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.TTPLM!,
      unlocode: "TTPLM",
      name: "Point Lisas",
      countryCode: "TT",
      region: "caribbean",
      lat: 10.3867,
      lng: -61.4725,
      maxDraftM: 13.5,
      maxLoaM: 290,
      maxBeamM: 40,
      maxDwtMt: 100_000,
      fuelTerminal: true,
      containerTerminal: false,
      bulkTerminal: true,
      reeferCapable: false,
      customsClearanceDaysMedian: 1.5,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: "Petrochemical-handling port — bunkering + LPG + ammonia",
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.DOHAI!,
      unlocode: "DOHAI",
      name: "Haina",
      countryCode: "DO",
      region: "caribbean",
      lat: 18.4100,
      lng: -70.0183,
      maxDraftM: 11.0,
      maxLoaM: 275,
      maxBeamM: 36,
      maxDwtMt: 65_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: false,
      customsClearanceDaysMedian: 2,
      portDaysMedian: 2.5,
      congestionFactor: 1.15,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.DOSDE!,
      unlocode: "DOSDE",
      name: "Santo Domingo",
      countryCode: "DO",
      region: "caribbean",
      lat: 18.4636,
      lng: -69.8846,
      maxDraftM: 10.0,
      maxLoaM: 260,
      maxBeamM: 34,
      maxDwtMt: 50_000,
      fuelTerminal: false,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: true,
      customsClearanceDaysMedian: 2.5,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "0600-1800",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.DOCBY!,
      unlocode: "DOCBY",
      name: "Caucedo",
      countryCode: "DO",
      region: "caribbean",
      lat: 18.4228,
      lng: -69.6250,
      maxDraftM: 14.0,
      maxLoaM: 366,
      maxBeamM: 49,
      maxDwtMt: 150_000,
      fuelTerminal: false,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: true,
      customsClearanceDaysMedian: 1.5,
      portDaysMedian: 1.5,
      congestionFactor: 1.0,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.HTPAP!,
      unlocode: "HTPAP",
      name: "Port-au-Prince",
      countryCode: "HT",
      region: "caribbean",
      lat: 18.5397,
      lng: -72.3408,
      maxDraftM: 9.5,
      maxLoaM: 220,
      maxBeamM: 32,
      maxDwtMt: 35_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: false,
      customsClearanceDaysMedian: 4,
      portDaysMedian: 3.5,
      congestionFactor: 1.4,
      workingHours: "0700-1700",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.BSNAS!,
      unlocode: "BSNAS",
      name: "Nassau",
      countryCode: "BS",
      region: "caribbean",
      lat: 25.0780,
      lng: -77.3386,
      maxDraftM: 9.0,
      maxLoaM: 300,
      maxBeamM: 42,
      maxDwtMt: 40_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: true,
      customsClearanceDaysMedian: 1.5,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "0700-1900",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.BBBGI!,
      unlocode: "BBBGI",
      name: "Bridgetown",
      countryCode: "BB",
      region: "caribbean",
      lat: 13.0978,
      lng: -59.6164,
      maxDraftM: 10.0,
      maxLoaM: 280,
      maxBeamM: 38,
      maxDwtMt: 50_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: true,
      customsClearanceDaysMedian: 2,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "0600-1800",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.CWWIL!,
      unlocode: "CWWIL",
      name: "Willemstad",
      countryCode: "CW",
      region: "caribbean",
      lat: 12.1150,
      lng: -68.9336,
      maxDraftM: 15.0,
      maxLoaM: 330,
      maxBeamM: 48,
      maxDwtMt: 130_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: true,
      customsClearanceDaysMedian: 1.5,
      portDaysMedian: 2,
      congestionFactor: 1.0,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.GYGEO!,
      unlocode: "GYGEO",
      name: "Georgetown",
      countryCode: "GY",
      region: "caribbean",
      lat: 6.8013,
      lng: -58.1551,
      maxDraftM: 5.5,
      maxLoaM: 180,
      maxBeamM: 28,
      maxDwtMt: 15_000,
      fuelTerminal: true,
      containerTerminal: false,
      bulkTerminal: true,
      reeferCapable: false,
      customsClearanceDaysMedian: 3,
      portDaysMedian: 3,
      congestionFactor: 1.2,
      workingHours: "0700-1700",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes:
        "Demerara river — tidal access, draft limited by bar channel",
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.SUPBM!,
      unlocode: "SUPBM",
      name: "Paramaribo",
      countryCode: "SR",
      region: "caribbean",
      lat: 5.8232,
      lng: -55.1679,
      maxDraftM: 6.0,
      maxLoaM: 200,
      maxBeamM: 30,
      maxDwtMt: 20_000,
      fuelTerminal: false,
      containerTerminal: false,
      bulkTerminal: true,
      reeferCapable: false,
      customsClearanceDaysMedian: 3,
      portDaysMedian: 3,
      congestionFactor: 1.1,
      workingHours: "0700-1700",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: "Suriname river — tidal access",
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.USHOU!,
      unlocode: "USHOU",
      name: "Houston",
      countryCode: "US",
      region: "usgc",
      lat: 29.7604,
      lng: -95.3698,
      maxDraftM: 13.7,
      maxLoaM: 330,
      maxBeamM: 46,
      maxDwtMt: 120_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: true,
      customsClearanceDaysMedian: 1,
      portDaysMedian: 2,
      congestionFactor: 1.05,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.USLAX!,
      unlocode: "USLAX",
      name: "Los Angeles",
      countryCode: "US",
      region: "uswc",
      lat: 33.7406,
      lng: -118.2760,
      maxDraftM: 16.0,
      maxLoaM: 400,
      maxBeamM: 62,
      maxDwtMt: 200_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: true,
      customsClearanceDaysMedian: 1,
      portDaysMedian: 2,
      congestionFactor: 1.1,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.USNYC!,
      unlocode: "USNYC",
      name: "New York",
      countryCode: "US",
      region: "usec",
      lat: 40.7128,
      lng: -74.0060,
      maxDraftM: 15.0,
      maxLoaM: 400,
      maxBeamM: 58,
      maxDwtMt: 200_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: true,
      reeferCapable: true,
      customsClearanceDaysMedian: 1,
      portDaysMedian: 2,
      congestionFactor: 1.05,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
    {
      ...base,
      id: SEED_PORT_IDS.USMIA!,
      unlocode: "USMIA",
      name: "Miami",
      countryCode: "US",
      region: "usec",
      lat: 25.7617,
      lng: -80.1918,
      maxDraftM: 14.0,
      maxLoaM: 330,
      maxBeamM: 44,
      maxDwtMt: 110_000,
      fuelTerminal: true,
      containerTerminal: true,
      bulkTerminal: false,
      reeferCapable: true,
      customsClearanceDaysMedian: 1,
      portDaysMedian: 1.5,
      congestionFactor: 1.0,
      workingHours: "24/7",
      pilotageRequired: true,
      tariffNotes: null,
      restrictedCargoNotes: null,
      localAgentOrgId: null,
      lastVerifiedAt: null,
      sourceReferences: [],
    },
  ];
}
