export const DB_CLIENT = Symbol("QUERY_DB_CLIENT");
export const RETRIEVAL_SERVICE = Symbol("QUERY_RETRIEVAL_SERVICE");
export const ANTHROPIC_ADAPTER = Symbol("QUERY_ANTHROPIC_ADAPTER");
export const OPENAI_ADAPTER = Symbol("QUERY_OPENAI_ADAPTER");
