export const MARKETING_DB_CLIENT = Symbol("MARKETING_DB_CLIENT");
export const MARKETING_SUMMARY_REPO = Symbol("MARKETING_SUMMARY_REPO");
export const MARKETING_CAMPAIGN_REPO = Symbol("MARKETING_CAMPAIGN_REPO");
export const MARKETING_EVENT_REPO = Symbol("MARKETING_EVENT_REPO");
export const MARKETING_TOUCHPOINT_REPO = Symbol("MARKETING_TOUCHPOINT_REPO");
