export const STRATEGY_DB_CLIENT = Symbol("STRATEGY_DB_CLIENT");
export const STRATEGY_WORKSPACES_REPO = Symbol("STRATEGY_WORKSPACES_REPO");
export const STRATEGY_EVENTS_REPO = Symbol("STRATEGY_EVENTS_REPO");
