export const VOICE_DB_CLIENT = Symbol("VOICE_DB_CLIENT");
export const VOICE_ANTHROPIC_ADAPTER = Symbol("VOICE_ANTHROPIC_ADAPTER");
export const VOICE_OPENAI_ADAPTER = Symbol("VOICE_OPENAI_ADAPTER");
export const VOICE_SESSION_STORE = Symbol("VOICE_SESSION_STORE");
export const VOICE_TRANSCRIPT_QUEUE = Symbol("VOICE_TRANSCRIPT_QUEUE");
export const VOICE_CONTEXT_BUILDER = Symbol("VOICE_CONTEXT_BUILDER");
